import { library } from '@fortawesome/fontawesome-svg-core';

import {
    faPlus,
    faPen,
    faTrashAlt,
    faPlusSquare,
    faAngleLeft,
    faGraduationCap,
    faBriefcase,
    faHome,
    faDumbbell,
    faBook,
    faHammer,
    faShoppingCart,
    faBirthdayCake,
    faBoxOpen,
    faCapsules,
    faDog,
    faLaptop,
    faPalette,
    faMusic
} from '@fortawesome/free-solid-svg-icons'

library.add(faPlus,
    faPlus,
    faPen,
    faTrashAlt,
    faPlusSquare,
    faAngleLeft,
    faGraduationCap,
    faBriefcase,
    faHome,
    faDumbbell,
    faBook,
    faHammer,
    faShoppingCart,
    faBirthdayCake,
    faBoxOpen,
    faCapsules,
    faDog,
    faLaptop,
    faPalette,
    faMusic)
